version: '3.6'
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Colombo
      - URL=apititan.works
      - VALIDATION=http
      - SUBDOMAINS=bindapidemo  #optional
      - CERTPROVIDER= #optional
      - DNSPLUGIN= #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      - EMAIL= chinthaka.deshapriya@gmail.com #optional
      - ONLY_SUBDOMAINS=true #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./appdata/swag/config:/config
    networks:
      bindapi-net:
        - ipv4_address: 172.25.0.5
    ports:
      - 443:443
      - 80:80 #optional
    restart: always

  pydnsapi:
    image: apititan/pydnsapi
    restart: always
    environment:
      - BIND_SERVER=${BIND_SERVER}
      - TSIG_USERNAME=${TSIG_USERNAME}
      - TSIG_PASSWORD=${TSIG_PASSWORD}
      - BIND_ALLOWED_ZONES=${BIND_ALLOWED_ZONES}
      - API_KEY_FILE=${API_KEY_FILE}
      - LOGGING_APPLICATION_NAME=${LOGGING_APPLICATION_NAME}
      - LOGGING_DIR=${LOGGING_DIR}
    volumes:
      - ./appdata/pydnsapi/logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      bindapi-net:
        - ipv4_address: 172.25.0.10
    
    bind9:
    image: internetsystemsconsortium/bind9:9.18
    restart: always
    environment:
    volumes: 
      - ./appdata/bind9/etc/bind:/etc/bind
      - ./appdata/bind9/var/cache/bind:/var/cache/bind
      - ./appdata/bind9/var/lib/bind:/var/lib/bind
      - ./appdata/bind9/var/log:/var/log  
      - ./config/bind/named.conf:/etc/bind/named.conf
      - ./config/bind/pydnsapi-bind9.conf:/etc/bind/pydnsapi-bind9.conf      
    networks:
      bindapi-net:
        - ipv4_address: 172.25.0.20
     
networks:
  bindapi-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
         
